seed: 1234
context_length: 30
epochs: 5
model_type: reward_conditioned
num_steps: 500000
num_buffers: 50
game: Breakout
batch_size: 128
trajectories_per_buffer: 10
data_dir_prefix: ./dqn_replay/
n_layer: 6
n_head: 8
n_embd: 128
n_regmask: 2
mask_mode: zero
traj_pmask: 0.15
reg_coef: 5
use_wandb: false
wandb_project_name: dt_atari_runs
run_name: ${game}-s${seed}-c${context_length}-r${n_regmask}_${mask_mode}_${traj_pmask}_${reg_coef}-${now:%m%dT%H%M}
save_ckpt: false
save_dir: ./outputs
save_results: false
prog_bar: true
log_interval: 100